### ISSUE TITLE
default bit size for master key

### ISSUE THREAD

**Issue by henrich** [lfit/itpol#27]
> Generate a 4096-bit RSA master key (ESSENTIAL)

But there's no reason why we should choose 4096 bit key in this guide, instead of default 2048/3072 bit key.

**Comment by mricon** [comment]
You're right -- the reasons are mostly social and not technical. We have  many respected cryptographers on the record stating that 2048-bit keys cannot be defeated without weakening RSA itself -- in which case 4096-bit keys will not offer much additional resistance. However, master keys happen to be the most visible ones on the keyservers and some of the developers you interact with will judge how good and paranoid you are based purely on the size of your key. Having a 4096-bit master key shuts them up. :)

I'll see if I can add this explanation into the guide.

**Comment by mricon** [comment]
Explained in 8a9d547
