### ISSUE TITLE
gpg: error reading key: No public key

### ISSUE THREAD

**Issue by bereska** [lfit/itpol#32]
I followed your guide and copied .gnupg to an encrypted external volume
but after running:
gpg2 --homedir=/volumes/gnupg/gnupg-backup --list-key [fpr]
i get this error
gpg: error reading key: No public key

**Comment by bereska** [comment]
sorry, never mind, my bad
i ran the wrong command, the correct one is:
gpg2 --homedir=/volumes/gnupg/gnupg-backup/.gnupg --list-key [fpr]
all is good now
thank you for a great tutorial

**Comment by bereska** [comment]
however I do have one more question, pls bare with me)
my existing pgp master key is [SC]
so if i remove it from ~/.gnupg/private-keys-v1.d, I won't be able to sign anything, right?
so I take it for this to work, Ii have to move both of my keys [SC] and [E] to an OpenPGP smart card, right?
by the way do you have any experience with Ledger Nano S/X? I currently use one for SSH and U2F. It would be great to move my keys to this device as well) 3 in 1 so to say)
thank you

**Comment by mricon** [comment]
You can create any number of [S] subkeys and they will all be considered valid, so you should make a new [S] subkey and then move your [SC] master key to offline storage.

**Comment by bereska** [comment]
Thank you
